// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFW_Deel_1.codes.ORM;

#nullable disable

namespace WPFW_Deel_1.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20241018152600_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WPFW_Deel_1.codes.ORM.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("value")
                        .HasColumnType("INTEGER");

                    b.HasKey("GradeID");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.ORM.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userID");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.ORM.Student", b =>
                {
                    b.HasBaseType("WPFW_Deel_1.codes.ORM.User");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.ORM.Teacher", b =>
                {
                    b.HasBaseType("WPFW_Deel_1.codes.ORM.User");

                    b.Property<string>("teachingCourse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userID1")
                        .HasColumnType("INTEGER");

                    b.HasIndex("userID1");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.ORM.Teacher", b =>
                {
                    b.HasOne("WPFW_Deel_1.codes.ORM.User", "user")
                        .WithMany()
                        .HasForeignKey("userID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
