// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFW_Deel_1.codes.API;

#nullable disable

namespace WPFW_Deel_1.Migrations.MovieDataBase
{
    [DbContext(typeof(MovieDataBaseContext))]
    partial class MovieDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.Property<int>("directorid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("moviesid")
                        .HasColumnType("INTEGER");

                    b.HasKey("directorid", "moviesid");

                    b.HasIndex("moviesid");

                    b.ToTable("DirectorMovie");
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.API.Director", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("directors");
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.API.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.API.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("movieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("movieId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.HasOne("WPFW_Deel_1.codes.API.Director", null)
                        .WithMany()
                        .HasForeignKey("directorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFW_Deel_1.codes.API.Movie", null)
                        .WithMany()
                        .HasForeignKey("moviesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.API.Review", b =>
                {
                    b.HasOne("WPFW_Deel_1.codes.API.Movie", "movie")
                        .WithMany("review")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");
                });

            modelBuilder.Entity("WPFW_Deel_1.codes.API.Movie", b =>
                {
                    b.Navigation("review");
                });
#pragma warning restore 612, 618
        }
    }
}
